[package]
name = "app"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
part00 = { path = "../part00" }
part01 = { path = "../part01" }
part02 = { path = "../part02" }
part03 = { path = "../part03" }
part04 = { path = "../part04" }
part05 = { path = "../part05" }
part06 = { path = "../part06" }
part07 = { path = "../part07" }
part08 = { path = "../part08" }
part09 = { path = "../part09" }
part10 = { path = "../part10" }
part11 = { path = "../part11" }
